/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnNodeIdRouteImport } from './routes/learn.$nodeId'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNodeIdRoute = LearnNodeIdRouteImport.update({
  id: '/learn/$nodeId',
  path: '/learn/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/recap': typeof RecapRoute
  '/tree': typeof TreeRoute
  '/learn/$nodeId': typeof LearnNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/recap': typeof RecapRoute
  '/tree': typeof TreeRoute
  '/learn/$nodeId': typeof LearnNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/recap': typeof RecapRoute
  '/tree': typeof TreeRoute
  '/learn/$nodeId': typeof LearnNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz' | '/recap' | '/tree' | '/learn/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/recap' | '/tree' | '/learn/$nodeId'
  id: '__root__' | '/' | '/quiz' | '/recap' | '/tree' | '/learn/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  RecapRoute: typeof RecapRoute
  TreeRoute: typeof TreeRoute
  LearnNodeIdRoute: typeof LearnNodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$nodeId': {
      id: '/learn/$nodeId'
      path: '/learn/$nodeId'
      fullPath: '/learn/$nodeId'
      preLoaderRoute: typeof LearnNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  RecapRoute: RecapRoute,
  TreeRoute: TreeRoute,
  LearnNodeIdRoute: LearnNodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
